import { useState } from "react";
import {
    FaTrophy, FaCheckCircle, FaExclamationCircle, FaRedo,
    FaDownload, FaChevronDown, FaChevronUp, FaStar, FaLightbulb
} from "react-icons/fa";

const InterviewScorecard = ({ evaluationResults, setupConfig, onRestart }) => {
    const [expandedQuestion, setExpandedQuestion] = useState(null);

    const {
        overallScore = 85,
        metrics = {
            technical: 88,
            communication: 82,
            problemSolving: 85,
            confidence: 85
        },
        strengths = [
            "Strong understanding of React component lifecycle and state hooks",
            "Clear articulation of async / await patterns in C# .NET",
            "Good problem decomposition under interview pressure"
        ],
        improvements = [
            "Elaborate more on database indexing and query optimization strategies",
            "Use STAR technique (Situation, Task, Action, Result) for behavioral questions"
        ],
        questionResults = []
    } = evaluationResults;

    const toggleQuestion = (index) => {
        setExpandedQuestion(expandedQuestion === index ? null : index);
    };

    const handleDownloadReport = () => {
        const reportContent = `
====================================================
           OPPORA AI MOCK INTERVIEW REPORT          
====================================================
Date: ${new Date().toLocaleDateString()}
Role: ${setupConfig.role} (${setupConfig.experience} Level)
Tech Stack: ${setupConfig.techStack.join(", ")}
Speech Mode: ${setupConfig.speechMode}

OVERALL INTERVIEW SCORE: ${overallScore}/100

METRIC BREAKDOWN:
- Technical Accuracy & Depth: ${metrics.technical}%
- Communication Clarity: ${metrics.communication}%
- Problem-Solving Logic: ${metrics.problemSolving}%
- Confidence & Delivery: ${metrics.confidence}%

KEY STRENGTHS:
${strengths.map(s => `- ${s}`).join("\n")}

AREAS FOR IMPROVEMENT:
${improvements.map(i => `- ${i}`).join("\n")}

QUESTION BY QUESTION REVIEW:
${questionResults.map((q, idx) => `
Q${idx + 1}: ${q.question}
Score: ${q.score}/100
Candidate Answer: ${q.userAnswer}
AI Feedback: ${q.feedback}
Ideal Model Answer: ${q.idealAnswer}
`).join("\n----------------------------------------------------\n")}

Report generated by Oppora AI Mock Interviewer
====================================================
        `;

        const blob = new Blob([reportContent], { type: "text/plain;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `AI_Mock_Interview_Scorecard_${setupConfig.roleId}_${Date.now()}.txt`;
        link.click();
        URL.revokeObjectURL(url);
    };

    const getScoreBadgeColor = (score) => {
        if (score >= 80) return "score-high";
        if (score >= 60) return "score-mid";
        return "score-low";
    };

    return (
        <div className="scorecard-container">
            {/* Header Banner */}
            <div className="scorecard-header">
                <div className="scorecard-title">
                    <div className="trophy-badge">
                        <FaTrophy />
                    </div>
                    <div>
                        <h2>Interview Performance Report</h2>
                        <p>{setupConfig.role} • {setupConfig.experience.toUpperCase()} Level • {setupConfig.techStack.join(", ")}</p>
                    </div>
                </div>

                <div className="overall-score-box">
                    <div className={`score-ring ${getScoreBadgeColor(overallScore)}`}>
                        <span className="score-num">{overallScore}</span>
                        <span className="score-max">/100</span>
                    </div>
                    <span className="score-verdict">
                        {overallScore >= 80 ? "🎉 Highly Recommended" : overallScore >= 60 ? "👍 Good Performance" : "💡 Practice Needed"}
                    </span>
                </div>
            </div>

            {/* Metrics Breakdown Grid */}
            <div className="metrics-grid">
                <div className="metric-card">
                    <div className="metric-header">
                        <span>Technical Accuracy</span>
                        <strong>{metrics.technical}%</strong>
                    </div>
                    <div className="progress-bar">
                        <div className="progress-fill tech-fill" style={{ width: `${metrics.technical}%` }}></div>
                    </div>
                </div>

                <div className="metric-card">
                    <div className="metric-header">
                        <span>Communication Clarity</span>
                        <strong>{metrics.communication}%</strong>
                    </div>
                    <div className="progress-bar">
                        <div className="progress-fill comm-fill" style={{ width: `${metrics.communication}%` }}></div>
                    </div>
                </div>

                <div className="metric-card">
                    <div className="metric-header">
                        <span>Problem Solving</span>
                        <strong>{metrics.problemSolving}%</strong>
                    </div>
                    <div className="progress-bar">
                        <div className="progress-fill ps-fill" style={{ width: `${metrics.problemSolving}%` }}></div>
                    </div>
                </div>

                <div className="metric-card">
                    <div className="metric-header">
                        <span>Confidence & Tone</span>
                        <strong>{metrics.confidence}%</strong>
                    </div>
                    <div className="progress-bar">
                        <div className="progress-fill conf-fill" style={{ width: `${metrics.confidence}%` }}></div>
                    </div>
                </div>
            </div>

            {/* Strengths & Improvements Row */}
            <div className="insights-grid">
                <div className="insight-card strengths-card">
                    <h4><FaCheckCircle className="icon-green" /> Key Strengths Identified</h4>
                    <ul>
                        {strengths.map((st, i) => (
                            <li key={i}>{st}</li>
                        ))}
                    </ul>
                </div>

                <div className="insight-card improvements-card">
                    <h4><FaExclamationCircle className="icon-orange" /> Growth Recommendations</h4>
                    <ul>
                        {improvements.map((imp, i) => (
                            <li key={i}>{imp}</li>
                        ))}
                    </ul>
                </div>
            </div>

            {/* Detailed Question Review */}
            <div className="questions-review-section">
                <h3>Detailed Question-by-Question Analysis</h3>
                <div className="q-accordion-list">
                    {questionResults.map((item, index) => (
                        <div key={index} className={`q-accordion-item ${expandedQuestion === index ? "expanded" : ""}`}>
                            <div className="q-accordion-header" onClick={() => toggleQuestion(index)}>
                                <div className="q-header-info">
                                    <span className="q-number">Q{index + 1}</span>
                                    <span className="q-text-snippet">{item.question}</span>
                                </div>
                                <div className="q-header-meta">
                                    <span className={`q-score-badge ${getScoreBadgeColor(item.score)}`}>
                                        {item.score}/100
                                    </span>
                                    {expandedQuestion === index ? <FaChevronUp /> : <FaChevronDown />}
                                </div>
                            </div>

                            {expandedQuestion === index && (
                                <div className="q-accordion-body">
                                    <div className="review-block">
                                        <h5>🗣️ Your Transcribed Response:</h5>
                                        <p className="user-response-text">{item.userAnswer || "No answer provided"}</p>
                                    </div>

                                    <div className="review-block">
                                        <h5>🤖 AI Evaluation Feedback:</h5>
                                        <p className="ai-feedback-text">{item.feedback}</p>
                                    </div>

                                    <div className="review-block ideal-block">
                                        <h5><FaLightbulb /> Model Answer Key Concepts:</h5>
                                        <p className="ideal-answer-text">{item.idealAnswer}</p>
                                    </div>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </div>

            {/* Footer Action Buttons */}
            <div className="scorecard-actions">
                <button type="button" className="restart-btn" onClick={onRestart}>
                    <FaRedo /> Practice Another Interview
                </button>

                <button type="button" className="download-report-btn" onClick={handleDownloadReport}>
                    <FaDownload /> Download Full Report (TXT)
                </button>
            </div>
        </div>
    );
};

export default InterviewScorecard;
